### ISSUE TITLE
Setting up routes for the backend

### ISSUE THREAD

**Issue by segfal** [segfal/layoff_tracker#6]

**Comment by segfal** [comment]
@AleHS01 
# TODO FOR baCKEND
- [x] Create a route where it gives every row corrosponding with the state
- [x] Create a route where it gives every row corresponding with the company
- [x] Create a route where it filters by date 
- [x] Create a route that filters if its laid off or closed
- [x] Pagination page filters should apply
- [x] Create a route to return all the states names - to create filter on front-end
